name: Update View

on:
  issues: 
    types: 
      - labeled
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  build-n-run:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      token: ${{ secrets.mytoken }}
      github_token : $GITHUB_TOKEN 
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name : Install Dependencies
      run : |
        python3 -m venv .env
        source .env/bin/activate
        pip install git+https://github.com/OpenPecha/Collection.git@create-meta
        chmod +x ./.github/scripts/set_token.sh
        sh ./.github/scripts/set_token.sh
    - name : Run update_view
      run : |
        source .env/bin/activate
        python3 ./.github/scripts/update_view.py ${{ github.event.issue.body }} $github_token