name: Update View

on:
  issues: 
    types: 
      - labeled
    labels:
     - bug
  
permissions:
  contents: write

jobs:
  build-n-run:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name : Install Dependencies
      run : |
        python3 -m venv .env
        source .env/bin/activate
        pip install git+https://github.com/OpenPecha/Collection.git@create-meta
    - name : Run update_view
      run : |
        source .env/bin/activate
        python3 ./.github/scripts/update_view.py ${{ github.event.issue.body }}
    - name: config git
      run: |
        git add -u
        git commit -m "updated views"
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: $GITHUB_TOKEN
        branch: main